const qs=[
['If your income increased by 30% starting next month, what would most likely happen?',['I would raise my lifestyle and allow myself things I had been putting off.','I would increase some expenses and try to keep part of the increase.','I would make a plan to divide the increase between saving, goals, and income growth.','I would direct most of the increase toward building assets or skills that could increase my future income.'],'system'],
['If your income stopped tomorrow, how long could you cover your essential expenses without borrowing?',['Less than one month.','One to three months.','Three to six months.','More than six months, and I also have another income source.'],'protection'],
['You receive an unexpected extra $1,000. What would you most likely do?',['Buy something I have wanted for a while.','Keep the money in cash in case I need it.','Split it between a current financial goal, emergency savings, or debt repayment.','First decide what would create the greatest long-term impact, such as paying expensive debt, building a buffer, or developing a skill or asset.'],'management'],
['At the end of the month, when you review your spending, which description fits you best?',['Sometimes I do not know where a large part of my money went.','I have a general idea of my spending, but I do not track it consistently.','I know my essential expenses and have clear spending limits.','I have a system that automatically allocates my income before I start spending.'],'management'],
['Which description best matches your current debt situation?',['Debt puts pressure on my monthly decisions.','I have debt, but I deal with it when I can.','I have a clear payoff plan and know what to prioritize.','My consumer debt is under control or nonexistent, and I work to keep it that way.'],'management'],
['You want to buy something that costs $1,500. What do you usually do?',['If the money is available, I buy it.','I wait a little and see if I still want it.','I compare options and make sure the purchase will not hurt my financial goals.','I already have money allocated for it and can buy it without disrupting my financial system.'],'system'],
['If you wanted to increase your income over the next year, what are you doing now?',['Waiting for a better opportunity or a raise.','Thinking about a few ideas, but I do not have a clear plan yet.','Working on a skill that could increase my value.','Following a specific plan to build a skill or new income source and giving it regular time.'],'growth'],
['Which statement best describes how you handle saving and investing?',['I save whatever is left at the end of the month.','I try to save, but the amount changes from month to month.','I set aside a fixed amount before spending.','I use automatic transfers so saving or investing happens without relying on a monthly decision.'],'system'],
['If you had an opportunity to increase your income but it required a lot of additional time, how would you think about it?',['I would take it as long as it increases my income.','I would take it temporarily if I needed the money.','I would compare the extra income with the cost to my time and life.','I would prefer building a skill or asset that can increase my income without relying entirely on more working hours.'],'growth'],
['You have a stable financial foundation and some money you will not need soon. What do you do?',['Keep it in cash because I do not want to take risks.','Look for an opportunity that seems profitable and decide based on what I find.','Learn about risks, goals, and suitable options first.','Follow a long-term strategy rather than chasing the latest opportunity.'],'growth'],
['You spent more than planned this month. What do you usually do?',['I assume the budget did not work and move on.','I try to make up for it next month.','I review what happened and adjust my plan.','I look for the root cause and change the system so the same mistake is harder to repeat.'],'system'],
['Which statement is closest to your definition of wealth?',['Being able to buy the things I want.','Having a good income and enough savings.','Being financially stable and having more choices in life.','Building a system of money, skills, and assets that gives me more choices over time.'],'growth']
];
let i=0,answers=[];const q=document.getElementById('q'),a=document.getElementById('a'),next=document.getElementById('next'),count=document.getElementById('count');
function render(){count.textContent=`Question ${i+1} of ${qs.length}`;q.textContent=qs[i][0];a.innerHTML='';qs[i][1].forEach((x,j)=>{const b=document.createElement('button');b.className='answer';b.textContent=x;b.type='button';if(answers[i]===j)b.classList.add('selected');b.onclick=()=>{answers[i]=j;document.querySelectorAll('.answer').forEach(v=>v.classList.remove('selected'));b.classList.add('selected');next.disabled=false};a.appendChild(b)});next.disabled=answers[i]===undefined;next.textContent=i===qs.length-1?'See my result':'Next →'}
function result(){const s={management:0,protection:0,growth:0,system:0},c={management:0,protection:0,growth:0,system:0};answers.forEach((v,n)=>{const k=qs[n][2];s[k]+=v+1;c[k]++});const d={};Object.keys(s).forEach(k=>d[k]=Math.round(s[k]/(c[k]*4)*100));const overall=Math.round(Object.values(d).reduce((x,y)=>x+y,0)/4);const profiles=overall<20?['Starter','You have a clear opportunity to build a stronger financial foundation. Focus first on stability, then build a simple system you can repeat.','Start by reviewing your spending and building an emergency buffer.']:overall<40?['Stabilizer','You have a useful foundation, but parts of your financial system need more stability and clarity.','Turn your financial goals into automatic rules instead of relying on monthly decisions.']:overall<60?['Organizer','You think in an organized way and already have several useful financial habits. Your next step is turning that organization into long-term growth.','Focus on increasing your income and gradually building assets.']:overall<80?['Builder','You have moved beyond many financial basics and are starting to think about money as a system for growth, not just spending.','Build a clear strategy around assets, skills, and income sources.']:['Wealth Builder','You have a long-term view and a relatively integrated financial system. Consistency and risk management now matter more than chasing quick solutions.','Keep your systems strong, review them regularly, and let compounding work in your favor.'];const labels={management:'Money Management',protection:'Financial Protection',growth:'Wealth Building',system:'System Strength'};const e=Object.entries(d).sort((x,y)=>y[1]-x[1]);document.getElementById('quiz').style.display='none';document.getElementById('result').style.display='block';document.getElementById('score').textContent=overall+'/100';document.getElementById('profile').textContent=profiles[0];document.getElementById('message').textContent=profiles[1];document.getElementById('dimensions').innerHTML=e.map(x=>'<p><strong>'+labels[x[0]]+'</strong> — '+x[1]+'%</p>').join('');document.getElementById('strength').textContent=labels[e[0][0]];document.getElementById('weakness').textContent=labels[e[3][0]];document.getElementById('nextStep').textContent=profiles[2];window.shareText='My Financial System Test score: '+overall+'/100 — '+profiles[0]+'\nhttps://thewealthsage.github.io/the-wealth-sage/pages/test.html'}
next.onclick=()=>{if(answers[i]===undefined)return;if(i<qs.length-1){i++;render()}else result()};document.getElementById('restart').onclick=()=>{i=0;answers=[];document.getElementById('result').style.display='none';document.getElementById('quiz').style.display='block';render()};document.getElementById('share').onclick=async()=>{if(navigator.share){await navigator.share({title:'My Financial System Test Result',text:window.shareText})}else{await navigator.clipboard.writeText(window.shareText);document.getElementById('share').textContent='Result copied'}};render();